In [1]:
import requests as rq
from bs4 import BeautifulSoup as bs
import pandas as pd

pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', 800)

In [2]:
URL = 'https://www.rbc.ru/'
HEADERS = {'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.93 Safari/537.36', 'accept': '*/*'}

In [3]:
def to_soup(url):
    page = rq.get(url, headers=HEADERS)
    return bs(page.text, 'html.parser')

In [4]:
def get_href(div):
    return div.find('a')['href']

In [5]:
def get_content(href):
    try:
        page_soup = to_soup(href)
        title = page_soup.find('div', {'class': 'article__header__title'}) .text
        overview = page_soup.find('div', {'class': 'article__text__overview'}).text
        text = '\n'.join([part.text for part in page_soup.find_all('p')])
        return {'Title': title, 'Text': f'{overview}\n{text}'}
    except AttributeError:
        return {'Title': None, 'Text': None}

In [6]:
main_soup = to_soup(URL)

In [7]:
articles = []
for art in main_soup.find_all('div', {'class': 'main__feed js-main-reload-item'}):
    href = get_href(art)
    articles.append(get_content(href))

In [8]:
df = pd.DataFrame(articles)
df = df.dropna()
df['Title'] = df['Title'].apply(lambda x: x.replace('\n', ' '))
df['Text'] = df['Text'].apply(lambda x: x.replace('\n', ' '))
df

                                                                                          Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Text
0                                    Кому предписана вакцинация в Москве и Подмосковье. Список    В Москве и Подмосковье 16 июня ввели обязательную вакцинацию от COVID-19 не менее 60% работающих. Первую дозу вакцины они должны получить до 15 июля, вторую — до 15 августа. Кого именно обязали привиться — в материале РБК  Вакцинацию против коронавируса в Москве и Подмосковье должны пройти государственные и муниципальные служащие столицы и области, сотрудники органов власти, а также работники:  сферы торговли; салонов красоты, косметических и СПА-салонов, соляриев, бань, саун, фитнес-клубов, физкультурно-оздоровительных центров, бассейнов; сферы бытовых услуг (прачечных, химчисток и других сервисов); сферы общественного питания; МФЦ, клиентских отделений в банках, почтовых отделений; общественного транспорта и такси; сферы образования, здравоохранения, социальной защиты; ЖКХ и энергет...
1                       Какие ограничения вводят регионы из-за новой вспышки COVID-19. Главное    В России начался резкий рост заболеваемости коронавирусом — количество ежедневно выявляемых случаев за неделю выросло на треть. На этом фоне регионы стали снова вводить ограничения. Главные из них — в материале РБК  В России ежедневно выявляемое число заражений с середины марта до 9 июня не превышало 10 тыс., а к середине июня перевалило за 14 тыс. — аналогичные показатели фиксировались в октябре. До половины ежедневного прироста случаев приходится на Москву — столица достигла декабрьской статистики. Москва    Как меняется число новых случаев заражения Covid-19 в России         Источник: федеральный и региональные оперштабы по борьбе с коронавирусом Данные по России i    Подмосковье Санкт-Петербург Также в городе:                   Video  Ивановская область    Карелия Хабаровский край...
2                             Песков описал настрой делегации Путина словами «не воевать едем»    По словам представителя президента, делегация Путина прибыла в Женеву с рабочим настроем. «Зачем боевое? Мы же не воевать едем», — пояснил Песков  Российская делегация едет на переговоры президента России Владимира Путина и президента США Джо Байдена с рабочим настроем, заявил пресс-секретарь российского президента Дмитрий Песков, передает «РИА Новости». «С обычным [настроем]. Зачем боевое? Мы же не воевать едем», — сказал Песков. Ранее в среду представитель российского президента говорил, что накануне переговоров в Женеве Москве «были посланы четкие сигналы», а также добавилась риторика «в пользу необходимости диалога». По словам Пескова, это является «бесспорным позитивом», который будет учитывать Путин. Основным вопросом на повестке переговоров являются двусторонние отношения Росси...
3                     Подмосковье вслед за Москвой ввело обязательную вакцинацию в сфере услуг    Работодатели из сфер общепита, транспорта, услуг, торговли и других должны вакцинировать не менее 60% сотрудников. Власти пояснили, что 70% заболевших COVID-19 составляет взрослое трудоспособное население  Работодателям компаний определенных сфер Московской области необходимо обеспечить вакцинацию от COVID-19 не менее 60% своих сотрудников, говорится в постановлении главного областного санитарного врача. Под распоряжение об обязательной вакцинации попали работники и представители сфер: Обязательная вакцинация также коснется государственных гражданских служащих, муниципальных служащих, работников органов власти Московской области и подведомственных организаций. До 15 июля работодателям поручено организовать вакцинацию первым компонентом вакцины (или однокомпонентным препаратом), до 15 ...
4                                             Собянин дал поручения по обязательной вакцинации    В Москве создадут информационную систему для контроля вакцинации, а работодатели должны будут передать в мэрию данные о сотрудниках, которым сделают прививки. Решение об обязательной вакцинации Собянин назвал «крайне тяжелым»  Мэр Москвы Сергей Собянин подписал указ в целях выполнения рекомендации главного государственного санитарного врача города об обязательной вакцинации работающих в сфере услуг. Согласно документу, в Москве до 1 июля создадут информационную систему, которая позволит проконтролировать, как выполняется постановление санитарного врача. Депздрав определит потребность в вакцине, холодильном оборудовании и прививочных бригадах, а организации и индивидуальные предприниматели должны будут предоставить на сайте мэрии сведения о сотрудниках, которым нужно пройти вакцинацию....
5                      В Подмосковье ввели ограничения для массовых мероприятий вместо запрета    Накануне Воробьев сообщил, что в городе на месяц запретили массовые мероприятия. Согласно новому постановлению, их можно проводить, но с условиями: социальная дистанция, не более 1,5 тыс. зрителей и билеты на конкретные места  Губернатор Московской области Андрей Воробьев подписал постановление, которое вводит ограничения на проведение массовых мероприятий до 20 июля. Проводить спортивные, физкультурные, досуговые, развлекательные, культурные и прочие мероприятия со зрителями, в том числе в закрытых помещениях, можно при одновременном выполнении следующих условий: Накануне Воробьев заявил, что проведение массовых мероприятий в области будет запрещено до 15 июля: «В течение месяца никаких массовых мероприятий на территории Подмосковья не будет». Такое решение он объяснил ростом заболев...
6                                 Собянин разрешил пользоваться скамейками в московских парках    За использование скамеек и «иных подобных объектов» городской инфраструктуры во время действия ограничительных мер, введенных в столице из-за пандемии, больше не будут штрафовать. Пункт указа изменили, исключив из него скамейки  Из указа мэра Москвы Сергея Собянина, в котором определены ограничения, вновь введенные столичными властями из-за роста числа случаев COVID-19, исчезло упоминание о запрете на использование скамеек в городских парках. Это следует из новой редакции документа, опубликованной на сайте мэрии. Поправка коснулась пункта 12.3 указа № 32-УМ «Об этапах снятия ограничений, установленных в связи с введением режима повышенной готовности». В предыдущей версии документа говорилось, что при посещении «территорий общегородского значения», к которым были отнесены в том числе г...
7                       О чем воронежцы написали экс-главе области Алексею Гордееву в соцсетях    В день России вице-спикер Госдумы и бывший воронежский губернатор опубликовал первые посты  «Здравствуйте, друзья! Это Алексей Гордеев» — так представил вице-спикер Госдумы свои аккаунты в Instagram, «ВКонтакте» и «Одноклассниках», выразив надежду, что они станут удобной площадкой для диалога, и призвав пользователей задавать вопросы и предложения по текущим проектам. Себя вице-спикер презентовал себя как общественного деятеля, заместителя председателя ГД РФ, члена Совета ГД РФ, доктора экономических наук, академика РАН. Пользователи «Одноклассников» отреагировали на предложение довольно активно, предъявив бывшему главе области претензии по поводу возможной разработки никелевых месторождений и «свиноцида» — массовой утилизации свиней во время вспышки АЧС в области. Пользователи VK обр...
8                               СМИ узнали об открытии ЕС для туристов из США и еще семи стран    В список также вошли Сербия, Тайвань, Албания, Ливан и еще три страны. Послабления будут касаться и тех приезжих оттуда, которые не прошли курс вакцинации. Таким образом число стран, из которых разрешено въезжать в ЕС, достигло 16  Евросоюз снимет ограничения для туристов из США на въезд в страны союза, сообщает AFP со ссылкой на источники. В список кроме США попадут еще семь государств: Как сообщает агентство, это касается и тех их резидентов, которые не были вакцинированы против COVID-19. ЕС несколько раз обновлял список, однако США и Россию в него до сих пор не включали. До этого в списке стран, для которых отменены ограничения на въезд в ЕС, значились восемь государств: Япония, Австралия, Израиль, Новая Зеландия, Руанда, Сингапур, Южная Корея и Таиланд.                            ...
9                                               Миллениалы назвали источник стресса номер один    Настроение у российской молодежи упало в 2021 году в среднем сильнее, чем у сверстников по миру, следует из отчета Deloitte. Еще в России молодые женщины почти в два раза чаще жаловались на постоянный стресс, чем мужчины  Тревожный год В 2021 году настроение молодых россиян — миллениалов и представителей поколения Z (зумеров) — упало сильнее, чем у их ровесников в мире. Если у последних оно снизилось в целом на три балла, то в России — на пять среди миллениалов и на семь у поколения Z. Об этом говорится в «Исследовании миллениалов и поколения Z в 2021 году в России» международной консалтинговой компании Deloitte (есть у РБК).         К миллениалам авторы отнесли людей, родившихся с января 1983 года по декабрь 1994-го, к зумерам — рожденных с января 1995 года до декабря 2003-го. Оценка...
10                                             Дюков назвал задачу сборной России на Евро-2020    Национальная команда намерена выйти из группы. Сегодня сборная России сыграет против финнов  Подписка отключает баннерную рекламу на сайтах РБК и обеспечивает его корректную работу Всего 99₽ в месяц для 3-х устройств Продлевается автоматически каждый месяц, но вы всегда сможете отписаться Сборной России поставлена задача выхода из группы на Евро-2020, заявил журналистам глава Российского футбольного союза (РФС) Александр Дюков. «Сборной России поставлена задача выхода из группы. Это непростая задача. Но будем надеяться, что она будет выполнена. И тренерский штаб, и команда настроены на это», — сказал Дюков. Первый матч на Евро-2020 сборная России проиграла бельгийцам со счетом 0:3 в Санкт-Петербурге. Впервые команда, которая на Евро являлась хозяйкой поля, потерпела крупное поражение....
11                                                    Первая встреча Путина и Байдена. Главное    В Женеве в среду пройдет первая встреча президентов России и США Владимира Путина и Джо Байдена. Главное о переговорах — в материале РБК  Ход встречи Президентов сопровождают делегации. Среди представителей России, кроме Лаврова: Что известно о планах президентов После завершения переговоров у президентов не будет совместной пресс-конференции. Каждый из них будет общаться с журналистами по отдельности. Кроме того, по итогам встречи никакие соглашения подписываться не будут, анонсировали в Кремле. Какие темы затронут на саммите По словам Ушакова, лидеры двух стран обсудят вопросы стратегической стабильности и кибербезопасности, российско-американские отношения, пандемию коронавируса, Украину, Ливию и Сирию, КНДР, Ближний Восток, урегулирование в Афганистане, на Корейском полуострове, в...
12                     Что происходит на вилле Ла Гранж перед встречей Путина и Байдена. Видео                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Считаные часы остаются до встречи президентов США и России Джо Байдена и Владимира Путина в Женеве. Журналисты, прибывшие на виллу Ла Гранж, где встретятся лидеры, ожидают «очень жаркий и длинный день»                    Video
13    Михаил Голосов  Непрозрачные реки: зачем нужен «речной Платон» и что бизнес о нем думает    В 2020 году Росморречфлот рассказал о планах ввести плату для судов за прохождение по внутренним водным путям. Систему окрестили «речным Платоном». Михаил Голосов (Hardfor) — о том, куда могут направить средства от транспортного сбора и в чем главный риск  Мы все помним, как сложно внедрялся «Платон»: забастовки и масштабные протесты длились несколько месяцев. Поэтому разговоры о речном «Платоне» сразу же вызывают негативную реакцию — люди ждут, какие проблемы начнутся, когда речь пойдет о реальном внедрении. Но не думаю, что нововведение может повлечь за собой масштабные протесты, как при введении «Платона». Автомобильные перевозки пока значительно популярнее речных. Кроме того, у бизнеса пока и не так много предварительной информации о «речном Платоне». Но дело не только в этом. Сит...

In [10]:
print(df['Title'][3])
print(df['Text'][3])

 Подмосковье вслед за Москвой ввело обязательную вакцинацию в сфере услуг
 Работодатели из сфер общепита, транспорта, услуг, торговли и других должны вакцинировать не менее 60% сотрудников. Власти пояснили, что 70% заболевших COVID-19 составляет взрослое трудоспособное население  Работодателям компаний определенных сфер Московской области необходимо обеспечить вакцинацию от COVID-19 не менее 60% своих сотрудников, говорится в постановлении главного областного санитарного врача. Под распоряжение об обязательной вакцинации попали работники и представители сфер: Обязательная вакцинация также коснется государственных гражданских служащих, муниципальных служащих, работников органов власти Московской области и подведомственных организаций. До 15 июля работодателям поручено организовать вакцинацию первым компонентом вакцины (или однокомпонентным препаратом), до 15 августа — вторым. Им также необходимо усилить информационно-разъяснительную работу среди сотрудников по вопросам профилактики коронавируса, «обратив особое внимание на необходимость проведения профилактических прививок».                            В Москве обязали вакцинировать 60% работающих                                        Общество        От обязательной вакцинации будут освобождены те, у кого есть противопоказания к прививке. В постановлении поясняется, что в регионе сложилась неблагополучная эпидемическая ситуация: суточное число новых случаев заболевания COVID-19 растет последние четыре недели, в период с 7 по 13 июня рост составил 13,1% по сравнению с предыдущей неделей. Наибольший удельный вес заболевших приходится на взрослое трудоспособное население в возрасте от 18 до 60 лет (70%), говорится в распоряжении. Также отмечается рост числа заболевших, которые активно до этого посещали общественные места и пользовались общественным транспортом.                            В Подмосковье запретили массовые мероприятия                                        Общество        Распоряжение об обязательной вакцинации в Подмосковье было опубликовано через несколько минут после аналогичного распоряжения санитарных властей Москвы. В столице также обязали вакцинировать не менее 60% сотрудников, работающих в сфере услуг. До 1 июля в городе будет создана информационная система с целью контролировать процесс достижения необходимых показателей вакцинации. За последние несколько дней Подмосковье усилило антикоронавирусные меры и контроль за их соблюдением. Так, в регионе ввели обязательный масочный режим. Средства защиты необходимо использовать в магазинах, аптеках, общественном транспорте, такси и в других местах. Организации обязали не допускать в здания граждан, не соблюдающих масочный режим. Изначально мера должна была действовать до 20 июня, но в среду обязательный масочный режим продлили еще на месяц, до 20 июля. Кроме того, в регионе запретили проведение массовых мероприятий до 15 июля.

In [11]:
rbk = pd.read_csv('/Users/darapetruhnenko/учеба/тексты/РБК')
rbk.drop(['Unnamed: 0'], axis=1, inplace=True)
rbk = rbk.append(df)

In [12]:
rbk

                                                                                          Title                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Text
0                                            Пандемия коронавируса. Самое актуальное на 23 мая    Число заразившихся COVID-19 в России превысило 5 млн человек, специалисты объяснили облегченный постковидный синдром у вакцинированных. Главные новости о коронавирусе — в обзоре РБК  Ситуация в России В России за последние сутки диагностировали 8951 новых случаев заражения коронавирусом, сообщил оперативный штаб. Общее число заболевших превысило  5 млн. Выздоровели 4,6 млн человек (плюс 7297 за сутки), умерли более 118 тыс. (плюс 357 за сутки). Год с COVID-19: как все было и что изменилось навсегда — в спецпроекте РБК    Как меняется число новых случаев заражения Covid-19 в России         Источник: федеральный и региональные оперштабы по борьбе с коронавирусом Данные по России i                                 Ситуация в мире По данным ВОЗ, число зараженных коронавирусом в мире превыс...
1                                                  «Евровидение» выиграла рок-группа из Италии    Победителем конкурса «Евровидение-2021» стала рок-группа из Италии Måneskin. Российская певица Manizha заняла девятое место  Победителем международного музыкального конкурса «Евровидение» стала итальянская рок-группа Måneskin, выступившая с песней Zitti E Buoni («Тихие и послушные»). По суммарным результатам зрительского голосования и жюри Måneskin получили 524 балла.       Второе место с 499 баллами заняла певица из Франции Барбара Прави. На третьей строчке — представитель Швейцарии Джон Мухарремай, выступивший под псевдонимом Gjon's Tears. Он получил 432 балла. Певица Manizha, представлявшая Россию, заняла девятое место. У нее 204 балла. Максимальные 12 баллов голосования жюри России в этом году поставил только Азербайджан. Всего жюри присудило Manizha 104 балла, еще 100 она получил...
2                                   Аналитики сравнили траты россиян на майских и на Новый год    Средний чек почти не изменился, но выросло общее количество транзакций, выяснил Райффайзенбанк. Рекордным стало 1 мая — в этот день клиенты потратили 1,7 млрд руб. Для сравнения: 1 января расходы составляли только 500 млн руб.  Жители России в минувшие длинные майские выходные потратили на 33% больше денег, чем во время новогодних каникул. Об этом сообщили аналитики Райффайзенбанка по результатам исследования расходов своих клиентов (есть у РБК). В то же время средние чеки не изменились, однако увеличилось количество транзакций: за первые 11 дней мая их было на 35% больше, чем за аналогичный период января. Если 1 января граждане совершили около полумиллиона транзакций, то 1 мая их было 1,4 млн. В каждый день весенних выходных число транзакций превышало 1 млн; в начале года такие превы...
3                        Болгарский бизнесмен рассказал о хранившемся на складе в Чехии оружии    На складах во Врбетице хранились старые боеприпасы, которые не предназначались для продажи, утверждает болгарский бизнесмен Емельян Гебрев. Ранее он говорил, что его компания после 2014 года поставляла оружие Украине  Оружие, хранившееся на складе в чешской деревне Врбетице, где в 2014 году произошли взрывы, не предназначалось для дальнейшей продажи, заявил в интервью Der Spiegel болгарский бизнесмен Емельян Гебрев. «Как и многие другие фирмы, наша компания арендовала склады во Врбетице. Мы хранили там старые боеприпасы времен Варшавского договора, которые приобрели в Чехии. Они были нужны для разных целей на производстве. Они не предназначались для продажи», — сказал Гебрев. Взрывы на складах во Вребетице произошли 16 октября и 3 декабря 2014 года. На них хранились боеприпасы, принад...
4                    СМИ узнали о тревоге США из-за размещения КНР руки-манипулятора в космосе    Китай продемонстрировал новую космическую разработку в виде руки-манипулятора, которую планируется разместить на будущей орбитальной станции. США полагают, что она может использоваться в военных целях  Развертывание Китаем роботизированной руки-манипулятора, которая будет установлена на основном модуле третьей по счету национальной космической орбитальной станции, вызвало опасения США. По мнению Вашингтона, она может быть использована в военных целях, пишет South China Morning Post. Несколько дней назад китайская аэрокосмическая научно-техническая корпорация (CASC) выпустила анимационный ролик, на котором была продемонстрирована одна из ее разработок. Это 10-метровая рука-манипулятор, способная поднимать объекты весом до 20 т и перемещаться за пределами орбитальной станции. Она состои...
..                                                                                          ...                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              ...
9                                               Миллениалы назвали источник стресса номер один    Настроение у российской молодежи упало в 2021 году в среднем сильнее, чем у сверстников по миру, следует из отчета Deloitte. Еще в России молодые женщины почти в два раза чаще жаловались на постоянный стресс, чем мужчины  Тревожный год В 2021 году настроение молодых россиян — миллениалов и представителей поколения Z (зумеров) — упало сильнее, чем у их ровесников в мире. Если у последних оно снизилось в целом на три балла, то в России — на пять среди миллениалов и на семь у поколения Z. Об этом говорится в «Исследовании миллениалов и поколения Z в 2021 году в России» международной консалтинговой компании Deloitte (есть у РБК).         К миллениалам авторы отнесли людей, родившихся с января 1983 года по декабрь 1994-го, к зумерам — рожденных с января 1995 года до декабря 2003-го. Оценка...
10                                             Дюков назвал задачу сборной России на Евро-2020    Национальная команда намерена выйти из группы. Сегодня сборная России сыграет против финнов  Подписка отключает баннерную рекламу на сайтах РБК и обеспечивает его корректную работу Всего 99₽ в месяц для 3-х устройств Продлевается автоматически каждый месяц, но вы всегда сможете отписаться Сборной России поставлена задача выхода из группы на Евро-2020, заявил журналистам глава Российского футбольного союза (РФС) Александр Дюков. «Сборной России поставлена задача выхода из группы. Это непростая задача. Но будем надеяться, что она будет выполнена. И тренерский штаб, и команда настроены на это», — сказал Дюков. Первый матч на Евро-2020 сборная России проиграла бельгийцам со счетом 0:3 в Санкт-Петербурге. Впервые команда, которая на Евро являлась хозяйкой поля, потерпела крупное поражение....
11                                                    Первая встреча Путина и Байдена. Главное    В Женеве в среду пройдет первая встреча президентов России и США Владимира Путина и Джо Байдена. Главное о переговорах — в материале РБК  Ход встречи Президентов сопровождают делегации. Среди представителей России, кроме Лаврова: Что известно о планах президентов После завершения переговоров у президентов не будет совместной пресс-конференции. Каждый из них будет общаться с журналистами по отдельности. Кроме того, по итогам встречи никакие соглашения подписываться не будут, анонсировали в Кремле. Какие темы затронут на саммите По словам Ушакова, лидеры двух стран обсудят вопросы стратегической стабильности и кибербезопасности, российско-американские отношения, пандемию коронавируса, Украину, Ливию и Сирию, КНДР, Ближний Восток, урегулирование в Афганистане, на Корейском полуострове, в...
12                     Что происходит на вилле Ла Гранж перед встречей Путина и Байдена. Видео                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Считаные часы остаются до встречи президентов США и России Джо Байдена и Владимира Путина в Женеве. Журналисты, прибывшие на виллу Ла Гранж, где встретятся лидеры, ожидают «очень жаркий и длинный день»                    Video
13    Михаил Голосов  Непрозрачные реки: зачем нужен «речной Платон» и что бизнес о нем думает    В 2020 году Росморречфлот рассказал о планах ввести плату для судов за прохождение по внутренним водным путям. Систему окрестили «речным Платоном». Михаил Голосов (Hardfor) — о том, куда могут направить средства от транспортного сбора и в чем главный риск  Мы все помним, как сложно внедрялся «Платон»: забастовки и масштабные протесты длились несколько месяцев. Поэтому разговоры о речном «Платоне» сразу же вызывают негативную реакцию — люди ждут, какие проблемы начнутся, когда речь пойдет о реальном внедрении. Но не думаю, что нововведение может повлечь за собой масштабные протесты, как при введении «Платона». Автомобильные перевозки пока значительно популярнее речных. Кроме того, у бизнеса пока и не так много предварительной информации о «речном Платоне». Но дело не только в этом. Сит...

[120 rows x 2 columns]

In [13]:
rbk.to_csv('/Users/darapetruhnenko/учеба/тексты/РБК')